CREATE DATABASE book_reviews;

USE book_reviews;

CREATE TABLE reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  imagePath VARCHAR(255),
  bookName VARCHAR(255),
  authorName VARCHAR(255),
  description TEXT,
  rating DOUBLE,
  reviewedBy VARCHAR(255),
  userName VARCHAR(255)
);

INSERT INTO reviews (imagePath, bookName, authorName, description, rating, reviewedBy, userName) VALUES
('images/Book_Image1.jpg', 'Book 1', 'Author 1', 'A fantastic read! Highly recommended.', 9.5, 'Reviewer 1', 'User1'),
('images/Book_Image1.jpg', 'Book 2', 'Author 2', 'Captivating story with memorable characters.', 8.0, 'Reviewer 2', 'User2'),
('images/Book_Image1.jpg', 'Book 3', 'Author 3', 'An engaging plot that keeps you hooked till the end.', 7.5, 'Reviewer 3', 'User3'),
('images/Book_Image1.jpg', 'Book 4', 'Author 4', 'Intriguing narrative with unexpected twists.', 8.5, 'Reviewer 4', 'User4'),
('images/Book_Image1.jpg', 'Book 5', 'Author 5', 'A classic tale that stands the test of time.', 9.0, 'Reviewer 5', 'User5'),
('images/Book_Image1.jpg', 'Book 6', 'Author 6', 'Compelling storyline that leaves a lasting impression.', 7.0, 'Reviewer 6', 'User6'),
('images/Book_Image1.jpg', 'Book 7', 'Author 7', 'Emotionally powerful and thought-provoking.', 8.0, 'Reviewer 7', 'User7'),
('images/Book_Image1.jpg', 'Book 8', 'Author 8', 'Well-written with richly developed characters.', 9.5, 'Reviewer 8', 'User8'),
('images/Book_Image1.jpg', 'Book 9', 'Author 9', 'A page-turner that you wont want to put down.', 8.5, 'Reviewer 9', 'User9'),
('images/Book_Image1.jpg', 'Book 10', 'Author 10', 'Gripping story that keeps you guessing.', 7.5, 'Reviewer 10', 'User10'),
('images/Book_Image1.jpg', 'Book 11', 'Author 11', 'Immersive world-building and vivid descriptions.', 9.0, 'Reviewer 11', 'User11'),
('images/Book_Image1.jpg', 'Book 12', 'Author 12', 'Complex characters and intricate plot.', 8.0, 'Reviewer 12', 'User12'),
('images/Book_Image1.jpg', 'Book 13', 'Author 13', 'Thoughtful and inspiring narrative.', 7.0, 'Reviewer 13', 'User13'),
('images/Book_Image1.jpg', 'Book 14', 'Author 14', 'Brilliantly crafted with surprising depth.', 9.5, 'Reviewer 14', 'User14'),
('images/Book_Image1.jpg', 'Book 15', 'Author 15', 'Beautifully written and emotionally resonant.', 8.5, 'Reviewer 15', 'User15'),
('images/Book_Image1.jpg', 'Book 16', 'Author 16', 'Suspenseful and thrilling from start to finish.', 7.5, 'Reviewer 16', 'User16'),
('images/Book_Image1.jpg', 'Book 17', 'Author 17', 'Compelling narrative with memorable moments.', 9.0, 'Reviewer 17', 'User17'),
('images/Book_Image1.jpg', 'Book 18', 'Author 18', 'Intriguing and thought-provoking.', 8.0, 'Reviewer 18', 'User18'),
('images/Book_Image1.jpg', 'Book 19', 'Author 19', 'Engrossing storyline with surprising twists.', 7.0, 'Reviewer 19', 'User19'),
('images/Book_Image1.jpg', 'Book 20', 'Author 20', 'Captivating and well-paced.', 9.5, 'Reviewer 20', 'User20'),
('images/Book_Image1.jpg', 'Book 21', 'Author 21', 'Entertaining and enjoyable read.', 8.5, 'Reviewer 21', 'User21'),
('images/Book_Image1.jpg', 'Book 22', 'Author 22', 'Full of adventure and excitement.', 7.5, 'Reviewer 22', 'User22'),
('images/Book_Image1.jpg', 'Book 23', 'Author 23', 'Unique and imaginative storytelling.', 9.0, 'Reviewer 23', 'User23'),
('images/Book_Image1.jpg', 'Book 24', 'Author 24', 'Compelling characters and vivid prose.', 8.0, 'Reviewer 24', 'User24'),
('images/Book_Image1.jpg', 'Book 25', 'Author 25', 'Thought-provoking and beautifully written.', 7.0, 'Reviewer 25', 'User25'),
('images/Book_Image1.jpg', 'Book 26', 'Author 26', 'An intriguing plot with unexpected twists.', 9.5, 'Reviewer 26', 'User26'),
('images/Book_Image1.jpg', 'Book 27', 'Author 27', 'Captivating and immersive storytelling.', 8.5, 'Reviewer 27', 'User27'),
('images/Book_Image1.jpg', 'Book 28', 'Author 28', 'A compelling narrative that captivates.', 7.5, 'Reviewer 28', 'User28'),
('images/Book_Image1.jpg', 'Book 29', 'Author 29', 'A gripping story that leaves an impact.', 9.0, 'Reviewer 29', 'User29'),
('images/Book_Image1.jpg', 'Book 30', 'Author 30', 'A mesmerizing tale with unexpected turns.', 8.0, 'Reviewer 30', 'User30'),
('images/Book_Image1.jpg', 'Book 31', 'Author 31', 'Thought-provoking and engaging.', 7.0, 'Reviewer 31', 'User31'),
('images/Book_Image1.jpg', 'Book 32', 'Author 32', 'An epic journey with richly developed characters.', 9.5, 'Reviewer 32', 'User32'),
('images/Book_Image1.jpg', 'Book 33', 'Author 33', 'Intricate plot and captivating storyline.', 8.5, 'Reviewer 33', 'User33'),
('images/Book_Image1.jpg', 'Book 34', 'Author 34', 'A thrilling read with unexpected twists.', 7.5, 'Reviewer 34', 'User34'),
('images/Book_Image1.jpg', 'Book 35', 'Author 35', 'Captivating narrative and compelling characters.', 9.0, 'Reviewer 35', 'User35'),
('images/Book_Image1.jpg', 'Book 36', 'Author 36', 'Engaging storyline and well-developed plot.', 8.0, 'Reviewer 36', 'User36'),
('images/Book_Image1.jpg', 'Book 37', 'Author 37', 'Thought-provoking and emotionally resonant.', 7.0, 'Reviewer 37', 'User37'),
('images/Book_Image1.jpg', 'Book 38', 'Author 38', 'Beautifully written with memorable moments.', 9.5, 'Reviewer 38', 'User38'),
('images/Book_Image1.jpg', 'Book 39', 'Author 39', 'An intriguing plot with surprising depth.', 8.5, 'Reviewer 39', 'User39'),
('images/Book_Image1.jpg', 'Book 40', 'Author 40', 'A captivating tale of love and adventure.', 7.5, 'Reviewer 40', 'User40'),
('images/Book_Image1.jpg', 'Book 41', 'Author 41', 'An enchanting story with vivid descriptions.', 9.0, 'Reviewer 41', 'User41'),
('images/Book_Image1.jpg', 'Book 42', 'Author 42', 'Suspenseful and thrilling from beginning to end.', 8.0, 'Reviewer 42', 'User42'),
('images/Book_Image1.jpg', 'Book 43', 'Author 43', 'A mesmerizing journey through time and space.', 7.0, 'Reviewer 43', 'User43'),
('images/Book_Image1.jpg', 'Book 44', 'Author 44', 'A compelling narrative with unexpected twists.', 9.5, 'Reviewer 44', 'User44'),
('images/Book_Image1.jpg', 'Book 45', 'Author 45', 'Emotionally powerful and deeply moving.', 8.5, 'Reviewer 45', 'User45'),
('images/Book_Image1.jpg', 'Book 46', 'Author 46', 'An engaging storyline with surprising twists.', 7.5, 'Reviewer 46', 'User46'),
('images/Book_Image1.jpg', 'Book 47', 'Author 47', 'Thought-provoking and beautifully written.', 9.0, 'Reviewer 47', 'User47'),
('images/Book_Image1.jpg', 'Book 48', 'Author 48', 'A gripping tale of adventure and courage.', 8.0, 'Reviewer 48', 'User48');
